// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: 001_players.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (id, created_at, updated_at, username, email, hashed_password)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, username, avatar, hashed_password, display_name, google_id, email, email_verified
`

type CreatePlayerParams struct {
	Username       string
	Email          sql.NullString
	HashedPassword sql.NullString
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayer, arg.Username, arg.Email, arg.HashedPassword)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Avatar,
		&i.HashedPassword,
		&i.DisplayName,
		&i.GoogleID,
		&i.Email,
		&i.EmailVerified,
	)
	return i, err
}

const createPlayerWithGoogle = `-- name: CreatePlayerWithGoogle :one

INSERT INTO players (id, created_at, updated_at, username, google_id, email, display_name, email_verified)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    TRUE
)
RETURNING id, created_at, updated_at, username, avatar, hashed_password, display_name, google_id, email, email_verified
`

type CreatePlayerWithGoogleParams struct {
	Username    string
	GoogleID    sql.NullString
	Email       sql.NullString
	DisplayName sql.NullString
}

func (q *Queries) CreatePlayerWithGoogle(ctx context.Context, arg CreatePlayerWithGoogleParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayerWithGoogle,
		arg.Username,
		arg.GoogleID,
		arg.Email,
		arg.DisplayName,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Avatar,
		&i.HashedPassword,
		&i.DisplayName,
		&i.GoogleID,
		&i.Email,
		&i.EmailVerified,
	)
	return i, err
}

const getPlayerByEmail = `-- name: GetPlayerByEmail :one

SELECT id, created_at, updated_at, username, avatar, hashed_password, display_name, google_id, email, email_verified FROM players
WHERE email = $1
`

func (q *Queries) GetPlayerByEmail(ctx context.Context, email sql.NullString) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByEmail, email)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Avatar,
		&i.HashedPassword,
		&i.DisplayName,
		&i.GoogleID,
		&i.Email,
		&i.EmailVerified,
	)
	return i, err
}

const getPlayerByGoogleId = `-- name: GetPlayerByGoogleId :one

SELECT id, created_at, updated_at, username, avatar, hashed_password, display_name, google_id, email, email_verified FROM players
WHERE google_id = $1
`

func (q *Queries) GetPlayerByGoogleId(ctx context.Context, googleID sql.NullString) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByGoogleId, googleID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Avatar,
		&i.HashedPassword,
		&i.DisplayName,
		&i.GoogleID,
		&i.Email,
		&i.EmailVerified,
	)
	return i, err
}

const getPlayerByPlayerId = `-- name: GetPlayerByPlayerId :one

SELECT id, created_at, updated_at, username, avatar, hashed_password, display_name, google_id, email, email_verified FROM players
WHERE id = $1
`

func (q *Queries) GetPlayerByPlayerId(ctx context.Context, id uuid.UUID) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByPlayerId, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Avatar,
		&i.HashedPassword,
		&i.DisplayName,
		&i.GoogleID,
		&i.Email,
		&i.EmailVerified,
	)
	return i, err
}

const getPlayerByRefreshToken = `-- name: GetPlayerByRefreshToken :one

SELECT id, players.created_at, players.updated_at, username, avatar, hashed_password, display_name, google_id, email, email_verified, token, refresh_tokens.created_at, refresh_tokens.updated_at, player_id, expires_at, revoked_at FROM players
LEFT JOIN refresh_tokens ON players.id = refresh_tokens.player_id
WHERE refresh_tokens.token = $1
`

type GetPlayerByRefreshTokenRow struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Username       string
	Avatar         sql.NullString
	HashedPassword sql.NullString
	DisplayName    sql.NullString
	GoogleID       sql.NullString
	Email          sql.NullString
	EmailVerified  sql.NullBool
	Token          sql.NullString
	CreatedAt_2    sql.NullTime
	UpdatedAt_2    sql.NullTime
	PlayerID       uuid.NullUUID
	ExpiresAt      sql.NullTime
	RevokedAt      sql.NullTime
}

func (q *Queries) GetPlayerByRefreshToken(ctx context.Context, token string) (GetPlayerByRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByRefreshToken, token)
	var i GetPlayerByRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Avatar,
		&i.HashedPassword,
		&i.DisplayName,
		&i.GoogleID,
		&i.Email,
		&i.EmailVerified,
		&i.Token,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.PlayerID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPlayerByUsername = `-- name: GetPlayerByUsername :one

SELECT id, created_at, updated_at, username, avatar, hashed_password, display_name, google_id, email, email_verified FROM players
WHERE username = $1
`

func (q *Queries) GetPlayerByUsername(ctx context.Context, username string) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByUsername, username)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Avatar,
		&i.HashedPassword,
		&i.DisplayName,
		&i.GoogleID,
		&i.Email,
		&i.EmailVerified,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :exec

UPDATE players
SET display_name = $2, avatar = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateProfileParams struct {
	ID          uuid.UUID
	DisplayName sql.NullString
	Avatar      sql.NullString
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateProfile, arg.ID, arg.DisplayName, arg.Avatar)
	return err
}

const verifyPlayerEmail = `-- name: VerifyPlayerEmail :exec

UPDATE players
SET email_verified = true, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) VerifyPlayerEmail(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, verifyPlayerEmail, id)
	return err
}
