// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: 001_players.sql

package database

import (
	"context"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (id, created_at, updated_at, username, hashed_password)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, username, avatar, hashed_password
`

type CreatePlayerParams struct {
	Username       string
	HashedPassword string
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayer, arg.Username, arg.HashedPassword)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Avatar,
		&i.HashedPassword,
	)
	return i, err
}
