// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Board struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Board     json.RawMessage
	PlayerID  uuid.UUID
	GameID    uuid.NullUUID
	Score     sql.NullInt32
}

type Game struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Board1     uuid.UUID
	Board2     uuid.NullUUID
	Winner     uuid.NullUUID
	PlayerTurn uuid.NullUUID
}

type Player struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Username       string
	Avatar         sql.NullString
	HashedPassword string
	DisplayName    sql.NullString
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	PlayerID  uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}
